# Generated by Django 4.1.1 on 2022-09-23 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("CompanyName", models.CharField(db_index=True, max_length=255)),
                (
                    "CompanyNumber",
                    models.CharField(
                        db_index=True, max_length=10, primary_key=True, serialize=False
                    ),
                ),
                (
                    "RegAddress_CareOf",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_POBox",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_AddressLine1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_AddressLine2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_PostTown",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_County",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_Country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "RegAddress_PostCode",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "CompanyCategory",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("private-unlimited", "PRIVATE_UNLIMITED"),
                            ("ltd", "LTD"),
                            ("plc", "PLC"),
                            ("old-public-company", "OLD_PUBLIC_COMPANY"),
                            (
                                "private-limited-guarant-nsc-limited-exemption",
                                "PRIVATE_LIMITED_GUARANT_NSC_LIMITED_EXEMPTION",
                            ),
                            ("limited-partnership", "LIMITED_PARTNERSHIP"),
                            (
                                "private-limited-guarant-nsc",
                                "PRIVATE_LIMITED_GUARANT_NSC",
                            ),
                            ("converted-or-closed", "CONVERTED_OR_CLOSED"),
                            ("private-unlimited-nsc", "PRIVATE_UNLIMITED_NSC"),
                            (
                                "private-limited-shares-section-30-exemption",
                                "PRIVATE_LIMITED_SHARES_SECTION_30_EXEMPTION",
                            ),
                            ("protected-cell-company", "PROTECTED_CELL_COMPANY"),
                            ("assurance-company", "ASSURANCE_COMPANY"),
                            ("oversea-company", "OVERSEA_COMPANY"),
                            ("eeig-establishment", "EEIG_ESTABLISHMENT"),
                            ("icvc-securities", "ICVC_SECURITIES"),
                            ("icvc-warrant", "ICVC_WARRANT"),
                            ("icvc-umbrella", "ICVC_UMBRELLA"),
                            (
                                "registered-society-non-jurisdictional",
                                "REGISTERED_SOCIETY_NON_JURISDICTIONAL",
                            ),
                            (
                                "industrial-and-provident-society",
                                "INDUSTRIAL_AND_PROVIDENT_SOCIETY",
                            ),
                            ("northern-ireland", "NORTHERN_IRELAND"),
                            ("northern-ireland-other", "NORTHERN_IRELAND_OTHER"),
                            ("llp", "LLP"),
                            ("royal-charter", "ROYAL_CHARTER"),
                            (
                                "investment-company-with-variable-capital",
                                "INVESTMENT_COMPANY_WITH_VARIABLE_CAPITAL",
                            ),
                            ("unregistered-company", "UNREGISTERED_COMPANY"),
                            ("other", "OTHER"),
                            (
                                "european-public-limited-liability-company-se",
                                "EUROPEAN_PUBLIC_LIMITED_LIABILITY_COMPANY_SE",
                            ),
                            ("united-kingdom-societas", "UNITED_KINGDOM_SOCIETAS"),
                            ("uk-establishment", "UK_ESTABLISHMENT"),
                            ("scottish-partnership", "SCOTTISH_PARTNERSHIP"),
                            (
                                "charitable-incorporated-organisation",
                                "CHARITABLE_INCORPORATED_ORGANISATION",
                            ),
                            (
                                "scottish-charitable-incorporated-organisation",
                                "SCOTTISH_CHARITABLE_INCORPORATED_ORGANISATION",
                            ),
                            (
                                "further-education-or-sixth-form-college-corporation",
                                "FURTHER_EDUCATION_OR_SIXTH_FORM_COLLEGE_CORPORATION",
                            ),
                            ("eeig", "EEIG"),
                            ("ukeig", "UKEIG"),
                            (
                                "registered-overseas-entity",
                                "REGISTERED_OVERSEAS_ENTITY",
                            ),
                            (
                                "community-interest-company",
                                "COMMUNITY_INTEREST_COMPANY",
                            ),
                            (
                                "private-fund-limited-partnership",
                                "PRIVATE_FUND_LIMITED_PARTNERSHIP",
                            ),
                        ],
                        db_index=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "CompanyStatus",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "CountryOfOrigin",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "DissolutionDate",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "IncorporationDate",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("Accounts_AccountRefDay", models.IntegerField(blank=True, null=True)),
                (
                    "Accounts_AccountRefMonth",
                    models.IntegerField(blank=True, null=True),
                ),
                ("Accounts_NextDueDate", models.DateField(blank=True, null=True)),
                ("Accounts_LastMadeUpDate", models.DateField(blank=True, null=True)),
                (
                    "Accounts_AccountCategory",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("null", "NULL"),
                            ("full", "FULL"),
                            ("small", "SMALL"),
                            ("medium", "MEDIUM"),
                            ("group", "GROUP"),
                            ("dormant", "DORMANT"),
                            ("interim", "INTERIM"),
                            ("initial", "INITIAL"),
                            ("total-exemption-full", "TOTAL_EXEMPTION_FULL"),
                            ("total-exemption-small", "TOTAL_EXEMPTION_SMALL"),
                            ("partial-exemption", "PARTIAL_EXEMPTION"),
                            (
                                "audit-exemption-subsidiary",
                                "AUDIT_EXEMPTION_SUBSIDIARY",
                            ),
                            (
                                "filing-exemption-subsidiary",
                                "FILING_EXEMPTION_SUBSIDIARY",
                            ),
                            ("micro-entity", "MICRO_ENTITY"),
                            (
                                "no-accounts-type-available",
                                "NO_ACCOUNTS_TYPE_AVAILABLE",
                            ),
                            ("audited-abridged", "AUDITED_ABRIDGED"),
                            ("unaudited-abridged", "UNAUDITED_ABRIDGED"),
                            ("no-accounts-filed", "NO_ACCOUNTS_FILED"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("Returns_NextDueDate", models.DateField(blank=True, null=True)),
                ("Returns_LastMadeUpDate", models.DateField(blank=True, null=True)),
                (
                    "Mortgages_NumMortCharges",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "Mortgages_NumMortOutstanding",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "Mortgages_NumMortPartSatisfied",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "Mortgages_NumMortSatisfied",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "LimitedPartnerships_NumGenPartners",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "LimitedPartnerships_NumLimPartners",
                    models.IntegerField(blank=True, null=True),
                ),
                ("URI", models.URLField(blank=True, max_length=255, null=True)),
                ("ConfStmtNextDueDate", models.DateField(blank=True, null=True)),
                ("ConfStmtLastMadeUpDate", models.DateField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("in_latest_update", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SICCode",
            fields=[
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PreviousName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ConDate", models.DateField(blank=True, null=True)),
                ("CompanyName", models.CharField(max_length=255)),
                ("in_latest_update", models.BooleanField(db_index=True, default=False)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="CompanyNumber",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_names",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "CompanyName")},
            },
        ),
        migrations.CreateModel(
            name="CompanySICCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_latest_update", models.BooleanField(db_index=True, default=False)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="CompanyNumber",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sic_codes",
                        to="companies.company",
                    ),
                ),
                (
                    "sic_code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sic_codes",
                        to="companies.siccode",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "sic_code")},
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year_end", models.DateField(db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("null", "NULL"),
                            ("full", "FULL"),
                            ("small", "SMALL"),
                            ("medium", "MEDIUM"),
                            ("group", "GROUP"),
                            ("dormant", "DORMANT"),
                            ("interim", "INTERIM"),
                            ("initial", "INITIAL"),
                            ("total-exemption-full", "TOTAL_EXEMPTION_FULL"),
                            ("total-exemption-small", "TOTAL_EXEMPTION_SMALL"),
                            ("partial-exemption", "PARTIAL_EXEMPTION"),
                            (
                                "audit-exemption-subsidiary",
                                "AUDIT_EXEMPTION_SUBSIDIARY",
                            ),
                            (
                                "filing-exemption-subsidiary",
                                "FILING_EXEMPTION_SUBSIDIARY",
                            ),
                            ("micro-entity", "MICRO_ENTITY"),
                            (
                                "no-accounts-type-available",
                                "NO_ACCOUNTS_TYPE_AVAILABLE",
                            ),
                            ("audited-abridged", "AUDITED_ABRIDGED"),
                            ("unaudited-abridged", "UNAUDITED_ABRIDGED"),
                            ("no-accounts-filed", "NO_ACCOUNTS_FILED"),
                        ],
                        db_index=True,
                        max_length=255,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        db_column="CompanyNumber",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "financial_year_end")},
            },
        ),
    ]
