# Generated by Django 4.1.5 on 2023-02-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_alter_company_options_alter_siccode_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="URI",
        ),
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("null", "NULL"),
                    ("full", "FULL"),
                    ("small", "SMALL"),
                    ("medium", "MEDIUM"),
                    ("group", "GROUP"),
                    ("dormant", "DORMANT"),
                    ("interim", "INTERIM"),
                    ("initial", "INITIAL"),
                    ("total-exemption-full", "TOTAL_EXEMPTION_FULL"),
                    ("total-exemption-small", "TOTAL_EXEMPTION_SMALL"),
                    ("partial-exemption", "PARTIAL_EXEMPTION"),
                    ("audit-exemption-subsidiary", "AUDIT_EXEMPTION_SUBSIDIARY"),
                    ("filing-exemption-subsidiary", "FILING_EXEMPTION_SUBSIDIARY"),
                    ("micro-entity", "MICRO_ENTITY"),
                    ("no-accounts-type-available", "NO_ACCOUNTS_TYPE_AVAILABLE"),
                    ("audited-abridged", "AUDITED_ABRIDGED"),
                    ("unaudited-abridged", "UNAUDITED_ABRIDGED"),
                    ("no-accounts-filed", "NO_ACCOUNTS_FILED"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="in_latest_update",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
