# Generated by Django 5.2.4 on 2025-08-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_alter_account_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="CompanyCategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assurance-company", "Assurance company"),
                    (
                        "charitable-incorporated-organisation",
                        "Charitable Incorporated Organisation",
                    ),
                    ("community-interest-company", "Community Interest Company"),
                    ("converted-or-closed", "Converted/Closed"),
                    ("eeig", "European Economic Interest Grouping (EEIG)"),
                    ("eeig-establishment", "EEIG Establishment"),
                    (
                        "european-public-limited-liability-company-se",
                        "European Public Limited-Liability Company (SE)",
                    ),
                    (
                        "further-education-or-sixth-form-college-corporation",
                        "Further education or sixth form college corporation",
                    ),
                    (
                        "icvc-securities",
                        "Investment Company with Variable Capital (Securities)",
                    ),
                    (
                        "icvc-umbrella",
                        "Investment Company with Variable Capital (Umbrella)",
                    ),
                    (
                        "icvc-warrant",
                        "Investment Company with Variable Capital (Warrant)",
                    ),
                    (
                        "industrial-and-provident-society",
                        "Industrial and Provident Society",
                    ),
                    (
                        "investment-company-with-variable-capital",
                        "Investment Company with Variable Capital",
                    ),
                    ("limited-partnership", "Limited Partnership"),
                    ("llp", "Limited Liability Partnership"),
                    ("ltd", "Private Limited Company"),
                    ("northern-ireland", "Northern Ireland"),
                    ("northern-ireland-other", "Northern Ireland Other"),
                    ("old-public-company", "Old Public Company"),
                    ("other", "Other company type"),
                    ("oversea-company", "Overseas company"),
                    ("plc", "Public Limited Company"),
                    (
                        "private-fund-limited-partnership",
                        "Private Fund Limited Partnership (PFLP)",
                    ),
                    (
                        "private-limited-guarant-nsc-limited-exemption",
                        "Company Limited by Guarantee (no share capital, use of 'Limited' exemption)",
                    ),
                    (
                        "private-limited-guarant-nsc",
                        "Company Limited by Guarantee (no share capital)",
                    ),
                    (
                        "private-limited-shares-section-30-exemption",
                        "Private limited company (section 30 of the Companies Act)",
                    ),
                    (
                        "private-unlimited-nsc",
                        "Private Unlimited Company (No Share Capital)",
                    ),
                    ("private-unlimited", "Private Unlimited Company"),
                    ("protected-cell-company", "Protected Cell Company"),
                    ("registered-overseas-entity", "Registered Overseas Entity"),
                    ("registered-society-non-jurisdictional", "Registered Society"),
                    ("royal-charter", "Royal Charter Company"),
                    (
                        "scottish-charitable-incorporated-organisation",
                        "Scottish Charitable Incorporated Organisation",
                    ),
                    ("scottish-partnership", "Scottish Partnership"),
                    ("uk-establishment", "United Kingdom Establishment"),
                    ("ukeig", "United Kingdom Economic Interest Grouping"),
                    ("united-kingdom-societas", "United Kingdom Societas"),
                    ("unregistered-company", "Unregistered Company"),
                    (
                        "authorised-company-service-provider",
                        "Authorised Company Service Provider",
                    ),
                ],
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Type",
            ),
        ),
    ]
