# Generated by Django 4.1.1 on 2022-09-27 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="siccode",
            options={"verbose_name": "SIC Code", "verbose_name_plural": "SIC Codes"},
        ),
        migrations.AlterField(
            model_name="company",
            name="CompanyStatus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "ACTIVE"),
                    ("active-proposal-to-strike-off", "ACTIVE_PROPOSAL_TO_STRIKE_OFF"),
                    ("dissolved", "DISSOLVED"),
                    ("liquidation", "LIQUIDATION"),
                    ("receivership", "RECEIVERSHIP"),
                    ("administration", "ADMINISTRATION"),
                    ("voluntary-arrangement", "VOLUNTARY_ARRANGEMENT"),
                    ("converted-closed", "CONVERTED_CLOSED"),
                    ("insolvency-proceedings", "INSOLVENCY_PROCEEDINGS"),
                    ("registered", "REGISTERED"),
                    ("removed", "REMOVED"),
                    ("closed", "CLOSED"),
                    ("open", "OPEN"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companysiccode",
            name="sic_code",
            field=models.ForeignKey(
                db_column="code",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="companies.siccode",
            ),
        ),
    ]
