# Generated by Django 4.1.5 on 2023-02-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_company_options_alter_siccode_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="URI",
        ),
        migrations.AlterField(
            model_name="company",
            name="in_latest_update",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
