# Generated by Django 4.1.5 on 2023-02-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "companies",
            "0004_alter_account_company_alter_companysiccode_company_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("null", "Null"),
                    ("full", "Full"),
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("group", "Group"),
                    ("dormant", "Dormant"),
                    ("interim", "Interim"),
                    ("initial", "Initial"),
                    ("total-exemption-full", "Total Exemption Full"),
                    ("total-exemption-small", "Total Exemption Small"),
                    ("partial-exemption", "Partial Exemption"),
                    ("audit-exemption-subsidiary", "Audit Exemption Subsidiary"),
                    ("filing-exemption-subsidiary", "Filing Exemption Subsidiary"),
                    ("micro-entity", "Micro Entity"),
                    ("no-accounts-type-available", "No accounts type available"),
                    ("audited-abridged", "Audited abridged"),
                    ("unaudited-abridged", "Unaudited abridged"),
                    ("no-accounts-filed", "Unaudited abridged"),
                ],
                db_index=True,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Accounts_AccountCategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("null", "Null"),
                    ("full", "Full"),
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("group", "Group"),
                    ("dormant", "Dormant"),
                    ("interim", "Interim"),
                    ("initial", "Initial"),
                    ("total-exemption-full", "Total Exemption Full"),
                    ("total-exemption-small", "Total Exemption Small"),
                    ("partial-exemption", "Partial Exemption"),
                    ("audit-exemption-subsidiary", "Audit Exemption Subsidiary"),
                    ("filing-exemption-subsidiary", "Filing Exemption Subsidiary"),
                    ("micro-entity", "Micro Entity"),
                    ("no-accounts-type-available", "No accounts type available"),
                    ("audited-abridged", "Audited abridged"),
                    ("unaudited-abridged", "Unaudited abridged"),
                    ("no-accounts-filed", "Unaudited abridged"),
                ],
                max_length=255,
                null=True,
                verbose_name="Account Category",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Accounts_AccountRefDay",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Account Reference Day"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Accounts_AccountRefMonth",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Account Reference Month"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Accounts_LastMadeUpDate",
            field=models.DateField(
                blank=True, null=True, verbose_name="Accounts last made up"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Accounts_NextDueDate",
            field=models.DateField(
                blank=True, null=True, verbose_name="Accounts next due"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="CompanyCategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assurance-company", "Assurance company"),
                    (
                        "charitable-incorporated-organisation",
                        "Charitable Incorporated Organisation",
                    ),
                    ("community-interest-company", "Community Interest Company"),
                    ("converted-or-closed", "Converted/Closed"),
                    ("eeig", "European Economic Interest Grouping (EEIG)"),
                    ("eeig-establishment", "EEIG Establishment"),
                    (
                        "european-public-limited-liability-company-se",
                        "European Public Limited-Liability Company (SE)",
                    ),
                    (
                        "further-education-or-sixth-form-college-corporation",
                        "Further education or sixth form college corporation",
                    ),
                    (
                        "icvc-securities",
                        "Investment Company with Variable Capital (Securities)",
                    ),
                    (
                        "icvc-umbrella",
                        "Investment Company with Variable Capital (Umbrella)",
                    ),
                    (
                        "icvc-warrant",
                        "Investment Company with Variable Capital (Warrant)",
                    ),
                    (
                        "industrial-and-provident-society",
                        "Industrial and Provident Society",
                    ),
                    (
                        "investment-company-with-variable-capital",
                        "Investment Company with Variable Capital",
                    ),
                    ("limited-partnership", "Limited Partnership"),
                    ("llp", "Limited Liability Partnership"),
                    ("ltd", "Private Limited Company"),
                    ("northern-ireland", "Northern Ireland"),
                    ("northern-ireland-other", "Northern Ireland Other"),
                    ("old-public-company", "Old Public Company"),
                    ("other", "Other company type"),
                    ("oversea-company", "Overseas company"),
                    ("plc", "Public Limited Company"),
                    (
                        "private-fund-limited-partnership",
                        "Private Fund Limited Partnership (PFLP)",
                    ),
                    (
                        "private-limited-guarant-nsc-limited-exemption",
                        "Company Limited by Guarantee (no share capital, use of 'Limited' exemption)",
                    ),
                    (
                        "private-limited-guarant-nsc",
                        "Company Limited by Guarantee (no share capital)",
                    ),
                    (
                        "private-limited-shares-section-30-exemption",
                        "Private limited company (section 30 of the Companies Act)",
                    ),
                    (
                        "private-unlimited-nsc",
                        "Private Unlimited Company (No Share Capital)",
                    ),
                    ("private-unlimited", "Private Unlimited Company"),
                    ("protected-cell-company", "Protected Cell Company"),
                    ("registered-overseas-entity", "Registered Overseas Entity"),
                    ("registered-society-non-jurisdictional", "Registered Society"),
                    ("royal-charter", "Royal Charter Company"),
                    (
                        "scottish-charitable-incorporated-organisation",
                        "Scottish Charitable Incorporated Organisation",
                    ),
                    ("scottish-partnership", "Scottish Partnership"),
                    ("uk-establishment", "United Kingdom Establishment"),
                    ("ukeig", "United Kingdom Economic Interest Grouping"),
                    ("united-kingdom-societas", "United Kingdom Societas"),
                    ("unregistered-company", "Unregistered Company"),
                ],
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="CompanyName",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Company Name"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="CompanyNumber",
            field=models.CharField(
                db_index=True,
                max_length=10,
                primary_key=True,
                serialize=False,
                verbose_name="Company Number",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="CompanyStatus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    (
                        "active-proposal-to-strike-off",
                        "Active - Proposal to Strike off",
                    ),
                    ("dissolved", "Dissolved"),
                    ("liquidation", "Liquidation"),
                    ("receivership", "Receivership"),
                    ("administration", "Administration"),
                    ("voluntary-arrangement", "Voluntary arrangement"),
                    ("converted-closed", "Converted/Closed"),
                    ("insolvency-proceedings", "Insolvency proceedings"),
                    ("registered", "Registered"),
                    ("removed", "Removed"),
                    ("closed", "Closed"),
                    ("open", "Open"),
                ],
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="ConfStmtLastMadeUpDate",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Confirmation statement last made up",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="ConfStmtNextDueDate",
            field=models.DateField(
                blank=True, null=True, verbose_name="Confirmation statement next due"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="CountryOfOrigin",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Country of Origin",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="DissolutionDate",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Dissolution Date"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="IncorporationDate",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Incorporation Date"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="LimitedPartnerships_NumGenPartners",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="General partners"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="LimitedPartnerships_NumLimPartners",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Limited partners"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Mortgages_NumMortCharges",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Mortgage charges"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Mortgages_NumMortOutstanding",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Outstanding mortgages"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Mortgages_NumMortPartSatisfied",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Partially satisfied mortgages"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Mortgages_NumMortSatisfied",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Satisfied mortgages"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="RegAddress_AddressLine1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="RegAddress_AddressLine2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address Line 2"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="RegAddress_CareOf",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Care Of"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="RegAddress_Country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="RegAddress_County",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="County"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="RegAddress_POBox",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PO Box"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="RegAddress_PostCode",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Post Code",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="RegAddress_PostTown",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Post Town"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Returns_LastMadeUpDate",
            field=models.DateField(
                blank=True, null=True, verbose_name="Returns last made up"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="Returns_NextDueDate",
            field=models.DateField(
                blank=True, null=True, verbose_name="Returns next due"
            ),
        ),
    ]
