# Generated by Django 5.0.4 on 2024-10-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommandLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=255)),
                ("cmd_options", models.TextField(blank=True, null=True)),
                ("started", models.DateTimeField(auto_now_add=True)),
                ("completed", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Running"),
                            (2, "Completed"),
                            (3, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("log", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
