# Generated by Django 5.0.4 on 2025-01-30 10:09

from django.db import migrations, models


def add_notified_and_updated(apps, schema_editor):
    CommandLog = apps.get_model("utils", "CommandLog")
    CommandLog.objects.filter(
        completed__isnull=False,
        updated__isnull=True,
    ).update(updated=models.F("completed"))
    CommandLog.objects.filter(
        started__isnull=False,
        updated__isnull=True,
    ).update(updated=models.F("started"))


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0002_alter_commandlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandlog",
            name="notified",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="When a notification was sent to admins",
            ),
        ),
        migrations.AddField(
            model_name="commandlog",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                verbose_name="When the command was last updated",
            ),
        ),
        migrations.RunPython(add_notified_and_updated),
        migrations.AlterField(
            model_name="commandlog",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="When the command was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="commandlog",
            name="completed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="When the command completed"
            ),
        ),
        migrations.AlterField(
            model_name="commandlog",
            name="started",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="When the command started"
            ),
        ),
    ]
