# Generated by Django 4.1.5 on 2023-01-13 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oscr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charity",
            options={
                "verbose_name": "Charity in Scotland",
                "verbose_name_plural": "Charities in Scotland",
            },
        ),
    ]
