# Generated by Django 4.2.2 on 2024-02-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccni", "0002_alter_charity_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charity",
            name="charitable_spending",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Charitable spending"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="date_for_financial_year_ending",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date for financial year ending"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="date_registered",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date registered"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="income_generation_and_governance",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Income generation and governance"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="retained_for_future_use",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Retained for future use"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="status",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="sub_charity_number",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Sub charity number"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="total_income",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Total income"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="total_spending",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Total spending"
            ),
        ),
    ]
