# Generated by Django 4.2.2 on 2024-04-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccni", "0003_alter_charity_charitable_spending_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charity",
            name="retained_for_future_use",
        ),
        migrations.RemoveField(
            model_name="charity",
            name="sub_charity_number",
        ),
        migrations.AddField(
            model_name="charity",
            name="assets_and_liabilities_total_fixed_assets",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Assets and liabilities - Total fixed assets",
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="charitable_purposes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Charitable purposes"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="employed_staff",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Employed staff"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="expenditure_on_charitable_activities",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Expenditure on Charitable activities",
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="expenditure_on_governance",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Expenditure on Governance"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="expenditure_on_other",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Expenditure on Other"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="expenditure_on_raising_funds",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Expenditure on Raising funds"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="financial_period_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Financial period end"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="financial_period_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Financial period start"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="income_from_charitable_activities",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Income from charitable activities"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="income_from_donations_and_legacies",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Income from donations and legacies"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="income_from_investments",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Income from investments"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="income_from_other",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Income from other"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="income_from_other_trading_activities",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Income from other trading activities",
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="other_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Other name"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="total_expenditure",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total expenditure"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="total_income_and_endowments",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total income and endowments"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="total_income_previous_financial_period",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Total income. Previous financial period.",
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="total_net_assets_and_liabilities",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Total net assets and liabilities"
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="type_of_governing_document",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Type of governing document",
            ),
        ),
        migrations.AddField(
            model_name="charity",
            name="uk_and_ireland_volunteers",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="UK and Ireland volunteers"
            ),
        ),
    ]
