# Generated by Django 5.0.4 on 2024-10-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccni", "0004_remove_charity_retained_for_future_use_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityclassification",
            name="charity",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classifications",
                to="ccni.charity",
                verbose_name="Charity",
            ),
        ),
    ]
