# Generated by Django 5.2.6 on 2026-06-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccni", "0005_alter_charityclassification_charity"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharityFinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_for_financial_year_ending",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date for financial year ending",
                    ),
                ),
                (
                    "total_income",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Total income"
                    ),
                ),
                (
                    "total_spending",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Total spending"
                    ),
                ),
                (
                    "charitable_spending",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Charitable spending"
                    ),
                ),
                (
                    "income_generation_and_governance",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Income generation and governance",
                    ),
                ),
                (
                    "financial_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Financial period start"
                    ),
                ),
                (
                    "financial_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Financial period end"
                    ),
                ),
                (
                    "total_income_previous_financial_period",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total income. Previous financial period.",
                    ),
                ),
                (
                    "employed_staff",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Employed staff"
                    ),
                ),
                (
                    "uk_and_ireland_volunteers",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="UK and Ireland volunteers"
                    ),
                ),
                (
                    "income_from_donations_and_legacies",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Income from donations and legacies",
                    ),
                ),
                (
                    "income_from_charitable_activities",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Income from charitable activities",
                    ),
                ),
                (
                    "income_from_other_trading_activities",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Income from other trading activities",
                    ),
                ),
                (
                    "income_from_investments",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Income from investments"
                    ),
                ),
                (
                    "income_from_other",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Income from other"
                    ),
                ),
                (
                    "total_income_and_endowments",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total income and endowments",
                    ),
                ),
                (
                    "expenditure_on_raising_funds",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Expenditure on Raising funds",
                    ),
                ),
                (
                    "expenditure_on_charitable_activities",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Expenditure on Charitable activities",
                    ),
                ),
                (
                    "expenditure_on_governance",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Expenditure on Governance"
                    ),
                ),
                (
                    "expenditure_on_other",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Expenditure on Other"
                    ),
                ),
                (
                    "total_expenditure",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total expenditure"
                    ),
                ),
                (
                    "assets_and_liabilities_total_fixed_assets",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Assets and liabilities - Total fixed assets",
                    ),
                ),
                (
                    "total_net_assets_and_liabilities",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total net assets and liabilities",
                    ),
                ),
                (
                    "charity",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_years",
                        to="ccni.charity",
                        verbose_name="Charity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charity Financial Year",
                "verbose_name_plural": "Charity Financial Years",
                "unique_together": {("charity_id", "date_for_financial_year_ending")},
            },
        ),
    ]
