# Generated by Django 5.2.4 on 2025-10-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charity",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
    ]
