# Generated by Django 5.2.4 on 2025-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crie", "0002_charity_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charity",
            name="latest_expenditure",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Latest Expenditure"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="latest_income",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="Latest Income"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="registered_charity_number",
            field=models.BigIntegerField(
                primary_key=True,
                serialize=False,
                verbose_name="Registered Charity Number",
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="cash_at_hand_and_in_bank",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Cash at Hand and in Bank"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="gross_expenditure",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Gross Expenditure"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="gross_income",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Gross Income"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="income_bequests",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Income: Bequests"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="income_donations",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Income: Donations"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="income_government_or_local_authorities",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                verbose_name="Income: Government or Local Authorities",
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="income_other_public_bodies",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Income: Other Public Bodies"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="income_other_sources",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Income: Other Sources"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="income_philantrophic_organisations",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                verbose_name="Income: Philantrophic Organisations",
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="income_trading_and_commercial_activities",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                verbose_name="Income: Trading and Commercial Activities",
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="net_assets_liabilities",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Net Assets / (Liabilities)"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="number_of_full_time_employees",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Number of Full-Time Employees"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="number_of_part_time_employees",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Number of Part-Time Employees"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="other_assets",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Other Assets"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="surplus_deficit_for_the_period",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Surplus / (Deficit) for the Period"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="total_assets",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Total Assets"
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="total_liabilities",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Total Liabilities"
            ),
        ),
    ]
