OAC11_SUBGROUPS = {
    "1A1": ["Rural workers and families", "Farming communities", "Rural residents"],
    "1A2": [
        "Established farming communities",
        "Farming communities",
        "Rural residents",
    ],
    "1A3": ["Agricultural communities", "Farming communities", "Rural residents"],
    "1A4": ["Older farming communities", "Farming communities", "Rural residents"],
    "1B1": ["Rural life", "Rural tenants", "Rural residents"],
    "1B2": ["Rural white-collar workers", "Rural tenants", "Rural residents"],
    "1B3": ["Ageing rural flat tenants", "Rural tenants", "Rural residents"],
    "1C1": [
        "Rural employment and retirees",
        "Ageing rural dwellers",
        "Rural residents",
    ],
    "1C2": ["Renting rural retirement", "Ageing rural dwellers", "Rural residents"],
    "1C3": ["Detached rural retirement", "Ageing rural dwellers", "Rural residents"],
    "2A1": ["Student communal living", "Students around campus", "Cosmopolitans"],
    "2A2": ["Student digs", "Students around campus", "Cosmopolitans"],
    "2A3": ["Students and professionals", "Students around campus", "Cosmopolitans"],
    "2B1": ["Students and commuters", "Inner city students", "Cosmopolitans"],
    "2B2": [
        "Multicultural student neighbourhood",
        "Inner city students",
        "Cosmopolitans",
    ],
    "2C1": ["Migrant families", "Comfortable cosmopolitan", "Cosmopolitans"],
    "2C2": ["Migrant commuters", "Comfortable cosmopolitan", "Cosmopolitans"],
    "2C3": [
        "Professional service cosmopolitans",
        "Comfortable cosmopolitan",
        "Cosmopolitans",
    ],
    "2D1": ["Urban cultural mix", "Aspiring and affluent", "Cosmopolitans"],
    "2D2": [
        "Highly-qualified quaternary workers",
        "Aspiring and affluent",
        "Cosmopolitans",
    ],
    "2D3": ["EU white-collar workers", "Aspiring and affluent", "Cosmopolitans"],
    "3A1": ["Established renting families", "Ethnic family life", "Ethnicity central"],
    "3A2": ["Young families and students", "Ethnic family life", "Ethnicity central"],
    "3B1": ["Striving service workers", "Endeavouring Ethnic Mix", "Ethnicity central"],
    "3B2": [
        "Bangladeshi mixed employment",
        "Endeavouring Ethnic Mix",
        "Ethnicity central",
    ],
    "3B3": [
        "Multi-ethnic professional service workers",
        "Endeavouring Ethnic Mix",
        "Ethnicity central",
    ],
    "3C1": ["Constrained neighbourhoods", "Ethnic dynamics", "Ethnicity central"],
    "3C2": ["Constrained commuters", "Ethnic dynamics", "Ethnicity central"],
    "3D1": ["New EU tech workers", "Aspirational techies", "Ethnicity central"],
    "3D2": ["Established tech workers", "Aspirational techies", "Ethnicity central"],
    "3D3": ["Old EU tech workers", "Aspirational techies", "Ethnicity central"],
    "4A1": [
        "Social renting young families",
        "Rented family living",
        "Multicultural metropolitans",
    ],
    "4A2": [
        "Private renting new arrivals",
        "Rented family living",
        "Multicultural metropolitans",
    ],
    "4A3": [
        "Commuters with young families",
        "Rented family living",
        "Multicultural metropolitans",
    ],
    "4B1": [
        "Asian terraces and flats",
        "Challenged Asian terraces",
        "Multicultural metropolitans",
    ],
    "4B2": [
        "Pakistani communities",
        "Challenged Asian terraces",
        "Multicultural metropolitans",
    ],
    "4C1": ["Achieving minorities", "Asian traits", "Multicultural metropolitans"],
    "4C2": [
        "Multicultural new arrivals",
        "Asian traits",
        "Multicultural metropolitans",
    ],
    "4C3": ["Inner city ethnic mix", "Asian traits", "Multicultural metropolitans"],
    "5A1": ["White professionals", "Urban professionals and families", "Urbanites"],
    "5A2": [
        "Multi-ethnic professionals with families",
        "Urban professionals and families",
        "Urbanites",
    ],
    "5A3": [
        "Families in terraces and flats",
        "Urban professionals and families",
        "Urbanites",
    ],
    "5B1": ["Delayed retirement", "Ageing urban living", "Urbanites"],
    "5B2": ["Communal retirement", "Ageing urban living", "Urbanites"],
    "5B3": ["Self-sufficient retirement", "Ageing urban living", "Urbanites"],
    "6A1": ["Indian tech achievers", "Suburban achievers", "Suburbanites"],
    "6A2": ["Comfortable suburbia", "Suburban achievers", "Suburbanites"],
    "6A3": ["Detached retirement living", "Suburban achievers", "Suburbanites"],
    "6A4": ["Ageing in suburbia", "Suburban achievers", "Suburbanites"],
    "6B1": ["Multi-ethnic suburbia", "Semi-detached suburbia", "Suburbanites"],
    "6B2": ["White suburban communities", "Semi-detached suburbia", "Suburbanites"],
    "6B3": ["Semi-detached ageing", "Semi-detached suburbia", "Suburbanites"],
    "6B4": ["Older workers and retirement", "Semi-detached suburbia", "Suburbanites"],
    "7A1": [
        "Transitional Eastern European neighbourhood",
        "Challenged diversity",
        "Constrained city dwellers",
    ],
    "7A2": ["Hampered aspiration", "Challenged diversity", "Constrained city dwellers"],
    "7A3": [
        "Multi-ethnic hardship",
        "Challenged diversity",
        "Constrained city dwellers",
    ],
    "7B1": [
        "Eastern European communities",
        "Constrained flat dwellers",
        "Constrained city dwellers",
    ],
    "7B2": [
        "Deprived neighbourhoods",
        "Constrained flat dwellers",
        "Constrained city dwellers",
    ],
    "7B3": [
        "Endeavouring flat dwellers",
        "Constrained flat dwellers",
        "Constrained city dwellers",
    ],
    "7C1": [
        "Challenged transitionaries",
        "White communities",
        "Constrained city dwellers",
    ],
    "7C2": [
        "Constrained young families",
        "White communities",
        "Constrained city dwellers",
    ],
    "7C3": ["Outer city hardship", "White communities", "Constrained city dwellers"],
    "7D1": [
        "Ageing communities and families",
        "Ageing city dwellers",
        "Constrained city dwellers",
    ],
    "7D2": [
        "Retired independent city dwellers",
        "Ageing city dwellers",
        "Constrained city dwellers",
    ],
    "7D3": [
        "Retired communal city dwellers",
        "Ageing city dwellers",
        "Constrained city dwellers",
    ],
    "7D4": [
        "Retired city hardship",
        "Ageing city dwellers",
        "Constrained city dwellers",
    ],
    "8A1": [
        "Industrious transitions",
        "Industrious communities",
        "Hard-pressed living",
    ],
    "8A2": ["Industrious hardship", "Industrious communities", "Hard-pressed living"],
    "8B1": [
        "Deprived blue-collar terraces",
        "Challenged terraced workers",
        "Hard-pressed living",
    ],
    "8B2": [
        "Hard pressed rented terraces",
        "Challenged terraced workers",
        "Hard-pressed living",
    ],
    "8C1": [
        "Ageing industrious workers",
        "Hard pressed ageing workers",
        "Hard-pressed living",
    ],
    "8C2": [
        "Ageing rural industry workers",
        "Hard pressed ageing workers",
        "Hard-pressed living",
    ],
    "8C3": [
        "Renting hard-pressed workers",
        "Hard pressed ageing workers",
        "Hard-pressed living",
    ],
    "8D1": [
        "Young hard-pressed families",
        "Migration and churn",
        "Hard-pressed living",
    ],
    "8D2": ["Hard-pressed ethnic mix", "Migration and churn", "Hard-pressed living"],
    "8D3": [
        "Hard-Pressed European Settlers",
        "Migration and churn",
        "Hard-pressed living",
    ],
}


RURAL_URBAN_IND = {
    "A1": [
        "Urban major conurbation",
        "England and Wales",
        "OA falls within a built-up area with a population of 10,000 or more and is assigned to the 'major conurbation' settlement category. The wider surrounding area is less sparsely populated",
    ],
    "B1": [
        "Urban minor conurbation",
        "England and Wales",
        "OA falls within a built-up area with a population of 10,000 or more and is assigned to the 'minor conurbation' settlement category. The wider surrounding area is less sparsely populated",
    ],
    "C1": [
        "Urban city and town",
        "England and Wales",
        "OA falls within a built-up area with a population of 10,000 or more and is assigned to the 'city and town' settlement category. The wider surrounding area is less sparsely populated",
    ],
    "C2": [
        "Urban city and town in a sparse setting",
        "England and Wales",
        "OA falls within a built-up area with a population of 10,000 or more and is assigned to the 'city and town' settlement category. The wider surrounding area is sparsely populated",
    ],
    "D1": [
        "Rural town and fringe",
        "England and Wales",
        "OA is assigned to the 'town and fringe' settlement category. The wider surrounding area is less sparsely populated",
    ],
    "D2": [
        "Rural town and fringe in a sparse setting",
        "England and Wales",
        "OA is assigned to the 'town and fringe' settlement category. The wider surrounding area is sparsely populated",
    ],
    "E1": [
        "Rural village",
        "England and Wales",
        "OA is assigned to the 'village' settlement category. The wider surrounding area is less sparsely populated",
    ],
    "E2": [
        "Rural village in a sparse setting",
        "England and Wales",
        "OA is assigned to the 'village' settlement category. The wider surrounding area is sparsely populated",
    ],
    "F1": [
        "Rural hamlet and isolated dwellings",
        "England and Wales",
        "OA is assigned to the 'hamlet and isolated dwelling' settlement category. The wider surrounding area is less sparsely populated",
    ],
    "F2": [
        "Rural hamlet and isolated dwellings in a sparse setting",
        "England and Wales",
        "OA is assigned to the 'hamlet and isolated dwelling' settlement category. The wider surrounding area is sparsely populated",
    ],
    "1": ["Large Urban Area", "Scotland", "Settlement of over 125,000 people"],
    "2": ["Other Urban Area", "Scotland", "Settlement of 10,000 to 125,000 people"],
    "3": [
        "Accessible Small Town",
        "Scotland",
        "Settlement of 3,000 to 10,000 people, within 30 minutes’ drive of a settlement of 10,000 or more",
    ],
    "4": [
        "Remote Small Town",
        "Scotland",
        "Settlement of 3,000 to 10,000 people, with a drive time of 30 to 60 minutes to a settlement of 10,000 or more",
    ],
    "5": [
        "Very Remote Small Town",
        "Scotland",
        "Settlement of 3,000 to 10,000 people, with a drive time of over 60 minutes to a settlement of 10,000 or more",
    ],
    "6": [
        "Accessible Rural",
        "Scotland",
        "Settlement of less than 3,000 people, within 30 minutes’ drive of a settlement of 10,000 or more",
    ],
    "7": [
        "Remote Rural",
        "Scotland",
        "Settlement of less than 3,000 people, with a drive time of 30 to 60 minutes to a settlement of 10,000 or more",
    ],
    "8": [
        "Very Remote Rural",
        "Scotland",
        "Settlement of less than 3,000 people, with a drive time of over 60 minutes to a settlement of 10,000 or more",
    ],
}
