# Generated by Django 4.1.5 on 2023-01-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccew", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charity",
            name="charity_is_cdf_or_cif",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CDF", "Common Deposit Fund"),
                    ("CIF", "Common Investment Fund"),
                ],
                help_text="Indicates whether the charity is a Common Investment Fund or Common Deposit Fund.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="charity_registration_status",
            field=models.CharField(
                blank=True,
                choices=[("Registered", "Registered"), ("Removed", "Removed")],
                db_index=True,
                help_text="The charity registration status indicates whether a charity is registered or removed",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="charity_reporting_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "New"),
                    ("Removed", "Removed"),
                    ("Submission Double Default", "Submission Double Default"),
                    ("Submission Overdue", "Submission Overdue"),
                    ("Submission Received", "Submission Received"),
                    ("Submission Received Late", "Submission Received Late"),
                    ("Suppressed", "Suppressed"),
                ],
                help_text="The current reporting status of the charity",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="charity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CIO", "CIO"),
                    ("Charitable company", "Charitable company"),
                    ("Other", "Other"),
                    ("Previously excepted", "Previously excepted"),
                    ("Trust", "Trust"),
                    ("Demonstration charity", "Demonstration charity"),
                ],
                db_index=True,
                help_text="The type of the charity displayed on the public register of charities. Only the main parent charity will have a value for this field (i.e. linked_charity_number=0).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charityothernames",
            name="charity_name_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Previous name", "Previous name"),
                    ("Working name", "Working name"),
                ],
                help_text="The type of other charity name. This can be working name or previous name.",
                max_length=255,
                null=True,
            ),
        ),
    ]
