# Generated by Django 4.1.5 on 2023-01-13 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ccew", "0002_alter_charity_charity_is_cdf_or_cif_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charity",
            options={
                "verbose_name": "Charity in England and Wales",
                "verbose_name_plural": "Charities in England and Wales",
            },
        ),
    ]
