# Generated by Django 4.2.2 on 2023-09-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccew", "0006_alter_merger_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="charityannualreturnhistory",
            constraint=models.UniqueConstraint(
                fields=("charity", "fin_period_end_date", "ar_cycle_reference"),
                name="unique_annual_return_history",
            ),
        ),
        migrations.AddConstraint(
            model_name="charityarparta",
            constraint=models.UniqueConstraint(
                fields=("charity", "fin_period_end_date"), name="unique_ar_parta"
            ),
        ),
        migrations.AddConstraint(
            model_name="charityarpartb",
            constraint=models.UniqueConstraint(
                fields=("charity", "fin_period_end_date"), name="unique_ar_partb"
            ),
        ),
    ]
