# Generated by Django 4.2.2 on 2023-10-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "ccew",
            "0007_charityannualreturnhistory_unique_annual_return_history_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityannualreturnhistory",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="annual_return_history",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityarparta",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="annual_return_part_a",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityarpartb",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="annual_return_part_b",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
    ]
