# Generated by Django 5.0.4 on 2024-10-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccew", "0008_alter_charityannualreturnhistory_charity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityannualreturnhistory",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="annual_return_history",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityareaofoperation",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_of_operation",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityarparta",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="annual_return_part_a",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityarpartb",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="annual_return_part_b",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityclassification",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classification",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityeventhistory",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_history",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charitygoverningdocument",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="governing_document",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityothernames",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_names",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityotherregulators",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_regulators",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charitypolicy",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charitypublishedreport",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_reports",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charitytrustee",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                db_constraint=False,
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trustees",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="merger",
            name="transferee",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merged_from",
                to="ccew.charity",
                verbose_name="Transferee",
            ),
        ),
        migrations.AlterField(
            model_name="merger",
            name="transferor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merged_into",
                to="ccew.charity",
                verbose_name="Transferor",
            ),
        ),
    ]
