# Generated by Django 5.2.4 on 2025-07-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccew", "0009_alter_charityannualreturnhistory_charity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharityAreaOfOperationLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geographic_area_type",
                    models.CharField(
                        db_index=True, help_text="The type of area", max_length=255
                    ),
                ),
                (
                    "geographic_area_description",
                    models.CharField(
                        db_index=True,
                        help_text="The area descriptor for this row",
                        max_length=255,
                    ),
                ),
                ("gss", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "iso3166_1",
                    models.CharField(
                        blank=True,
                        default="GB",
                        help_text="The ISO3166:1 alpha 2 code for the area, if applicable",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "iso3166_1_alpha3",
                    models.CharField(
                        blank=True,
                        default="GBR",
                        help_text="The ISO3166:1 alpha 3 code for the area, if applicable",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "iso3166_2_gb",
                    models.CharField(
                        blank=True,
                        help_text="The ISO3166:2 code for the area in the UK, if applicable",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        blank=True,
                        help_text="The continent for the area, if applicable",
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
