# Generated by Django 4.1.5 on 2023-01-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ccew", "0003_alter_charity_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transferor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transferor_regno",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transferor_subno",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transferee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transferee_regno",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transferee_subno",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_vesting_declaration",
                    models.DateField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_property_transferred",
                    models.DateField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_merger_registered",
                    models.DateField(blank=True, max_length=255, null=True),
                ),
                (
                    "transferee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merged_from",
                        to="ccew.charity",
                        verbose_name="Transferee",
                    ),
                ),
                (
                    "transferor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merged_into",
                        to="ccew.charity",
                        verbose_name="Transferor",
                    ),
                ),
            ],
        ),
    ]
