# Generated by Django 4.1.5 on 2023-01-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccew", "0004_merger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merger",
            name="transferee_regno",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="merger",
            name="transferee_subno",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="merger",
            name="transferor_regno",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="merger",
            name="transferor_subno",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
