# Generated by Django 5.0.4 on 2024-10-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geocode",
            name="ENTITYCD",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                max_length=3,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="geo_codes",
                to="postcodes.geoentity",
                verbose_name="Entity code",
            ),
        ),
        migrations.AlterField(
            model_name="geoentity",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entities",
                to="postcodes.geoentitygroup",
                verbose_name="Entity group",
            ),
        ),
    ]
