# Generated by Django 5.2.4 on 2025-09-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcodes", "0002_alter_geocode_entitycd_alter_geoentity_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcode",
            name="RU21IND",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="2021 Census rural-urban classification",
            ),
        ),
    ]
