# Generated by Django 5.2.4 on 2026-10-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcodes", "0003_postcode_ru21ind"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcode",
            name="OAC21",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                verbose_name="2021 Census Output Area classification (OAC)",
            ),
        ),
    ]
